<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.8.10 on linux)" generated="20230302 15:27:42.388" rpa="false" schemaversion="3">
<suite id="s1" name="testVnf etsi" source="/home/chrisys/tutorials/4-test_your_vnfs_with_robot_framework/VNF_ETSI_Test/testVnf_etsi.robot">
<test id="s1-t1" name="Testing if the validation output is %{VNF_VALID}" line="5">
<kw name="Vnf Etsi" library="vnf_etsi">
<var>${vnf_val}</var>
<msg timestamp="20230302 15:27:42.980" level="INFO">[!] Cannot connect to the SSH Server</msg>
<errors>
<msg timestamp="20230302 15:27:42.981" level="ERROR">Execution stopped by user.</msg>
</errors>
</robot>
